### ISSUE TITLE
syntax highlighting fails when using codeOutput alongside plotOutput

### ISSUE THREAD

**Issue by EvaMaeRey** [statistikat/codeModules#2]
Hello! codeModules seems really cool!   

I'm interested in using highlighted code outputs alongside plot outputs.  However, when I include a plot output, I'm not seeing the syntax highlighting persist.  If plot is not included, code highlighting looks great! Would appreciate any insights!

```r
shinyApp(
  fluidPage(
    mainPanel(
    codeOutput("code_out"),
    plotOutput("plot_out")
    )
  ),

  function(input, output, session){

    output$code_out <- renderCode({
      "1+1"
    })


    output$plot_out <- renderPlot({
      ggplot(cars) + aes(speed, dist) + geom_point()

    })
  }
)
```

**Comment by GregorDeCillia** [comment]
Thank you for those kind words @EvaMaeRey . You can get this to work using the `delay` parameter of `renderCode()`. 

```r
output$code_out <- renderCode({"1+1"}, delay = 1000)
```

This parameter defines how many milliseconds javascript should wait before invoking the highlight logic. It seems the default (100 milliseconds) is not enough which will lead to the highlighter getting to work before the code string arrives in the ui.

If you are not sure what delay is appropriate, you can also set multiple values which will invoke the highlighter several times.

```r
output$code_out <- renderCode({"1+1"}, delay = c(100, 500, 1000, 2000))
```

**Comment by EvaMaeRey** [comment]
Ah!  Thank you for this diagnosis and remedy!  Code is highlighting nicely.  I see a bit of a flicker upon update (back to plain text for a moment).  I don't know if there is something that can be done about that.  I want to explore codeModules some more!

library(shiny) 
library(ggplot2)
shinyApp(
   fluidPage(
     sidebarPanel(
     selectInput(inputId = "char_color",
                               label = "color",
                               selected = "magenta",
                               choices = colors()
   )),
     mainPanel(
     codeOutput("code_out"),
     plotOutput("plot_out")
     )
   ),

   function(input, output, session){


     output$code_out <- renderCode({
       paste0("1+1 +'", input$char_color, "'")
     }, delay = c(100, 500, 1000))


     output$plot_out <- renderPlot({
       ggplot(cars) + aes(speed, dist) + geom_point(color = input$char_color)

     })
   }
 )

**Comment by GregorDeCillia** [comment]
The flashing is because of the time between the string arriving in the ui and the highlighter going to work. You could try setting even more delay values until the unhighlighted state is no longer noticeable

```r
output$code_out <- renderCode({
      paste0("1+1 +'", input$char_color, "'")
}, delay = c(100, 200, 300, 400, 500, 1000))
```

Another option is to switch to a specialized package for highlighting. There are three packages that I would recommend specifically.

* `shinyAce` can be used as a fancy text input and supports various languages. In read-only mode it can also act as a syntax highlighter. ace-editor (the js library) is used by rstudio so if you are an rstudio user, the styles will be very familiar
* `cli` is meant to be used in the console for colored terminal output. But those "terminal colors" can be translated into html markup via `fansi::to_html()`
* `downlit` is used by `pkgown` and automatically generates links to help pages - in this case, you will be directed to the ggplot2 website if you click on `ggplot` or `aes`. This is very useful if the codes are intended for teaching

```r
# install.packages("cli")
# install.packages("fansi")
# install.packages("shinyAce")
# install.packages("downlit")
library(shiny)
library(ggplot2)
library(magrittr)
shinyApp(
  fluidPage(
    sidebarPanel(
      selectInput(inputId = "char_color",
                  label = "color",
                  selected = "magenta",
                  choices = colors()
      ),
      selectInput("theme_cli", "code theme (cli)",
                  cli::code_theme_list(),
                  selected = "Crimson Editor"),
      selectInput("theme_ace", "code theme (ace)",
                  shinyAce::getAceThemes())
    ),
    mainPanel(
      codeOutput("code_out"),
      uiOutput("code_out2"),
      uiOutput("code_out3"),
      shinyAce::aceEditor("ace", "", "r", height = "62px",
                          readOnly = TRUE, fontSize = 16, 
                          showLineNumbers = FALSE,
                          highlightActiveLine = FALSE),
      plotOutput("plot_out")
    )
  ),
  
  function(input, output, session){
    code <- reactive({
      sprintf('library(ggplot2)\nggplot(cars) + aes(speed, dist) + \n    geom_point(color = "%s")',
              input$char_color)
    })
    
    output$code_out <- renderCode({
      code()
    }, delay = c(100, 200, 300, 400, 500, 1000))
    output$code_out2 <- renderUI({      
      code() %>% 
        cli::code_highlight(code_theme = input$theme_cli) %>% 
        fansi::html_esc() %>% fansi::to_html() %>% 
        HTML() %>% tags$pre()
    })
    observeEvent(input$char_color, {
      shinyAce::updateAceEditor(session, "ace", code())
    })
    observeEvent(input$theme_ace, {
      shinyAce::updateAceEditor(session, "ace", theme = input$theme_ace)
    })
    output$plot_out <- renderPlot({
      ggplot(cars) + aes(speed, dist) + geom_point(color = input$char_color)
    })
    output$code_out3 <- renderUI({
      code_html <- code() %>% downlit::highlight() %>% HTML()
      code_css <- "pre .s {color: green}\n pre .o {color: #8400a9}" %>% 
        HTML() %>% tags$style() 
      tagList(tags$pre(code_html), code_css)
    })
  }
)
```
